# Original template generated by:
#   clang-format -style=google -dump-config > clang-format.cfg
clang-format -style=file:clang-format.cfg -i ./kernel/src/*.cpp
clang-format -style=file:clang-format.cfg -i ./kernel/include/*.hpp
clang-format -style=file:clang-format.cfg -i ./kernel/arch/armv7m/*.cpp

